version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./server/:/app
    networks:
      - my-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root123@md
      POSTGRES_DB: cadastro
    # volumes:
    #   - ./db-data:/var/lib/postgresql/data
    ports:
      - 5050:5432
    networks:
      - my-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Root123@md
    restart: always
    ports:
      - "5052:80"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client/:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge